# Generated by Django 4.1.7 on 2024-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='autor', to='zgloszenia.report'),
        ),
    ]
