# Generated by Django 4.1.7 on 2024-01-02 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0002_alter_customuser_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='notifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zgloszajacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
