# Generated by Django 4.1.7 on 2024-01-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0004_alter_report_notifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='notifier',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
