# Generated by Django 4.1.7 on 2024-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0005_remove_report_notifier_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
